# Automatically generated by pb2py
# fmt: off
if False:
    from typing_extensions import Literal

BITCOIN = 0  # type: Literal[0]
MILLIBITCOIN = 1  # type: Literal[1]
MICROBITCOIN = 2  # type: Literal[2]
SATOSHI = 3  # type: Literal[3]
